### ISSUE TITLE
how to not zip output

### ISSUE THREAD

**Issue by raerickson** [blaxterlab/ncbi-blast-docker#1]
@sujaikumar Thank you for writing this helpful Docker image! 

I've tried forking your image and not using `gzip` on the output, but I have not been able to get the code to work. How would one modify the `blast.pl` file to not gzip the output? I've tried removing `gzip | out.gz` at the end of line 31, but that produced no output file. 

The reason I do not want to zip my output files is that zipping them doubles the run time for each job.

**Comment by sujaikumar** [comment]
Hi there. Just change `| gzip > $out.gz` to `> $out` in `blast.pl`

We like saving things as gz files because you can always unzip them on the fly without actually spending time gunzipping the file first, eg:

```
gunzip -c out.gz | cut -f1,2 | sort | uniq | wc -l
#or
zcat out.gz | cut -f1,2 | sort | uniq | wc -l
```
etc

**Comment by raerickson** [comment]
Thank you for the help!

Also, for anybody else reading this thread, not using gzip only saved ~3 minutes on an hour long run of 21 test file.

**Comment by sujaikumar** [comment]
Glad you found it useful!

Yes, that's why we do gzipping on the fly... (i.e. you do it while piping
the output, or gunzipping while piping the input afterwards) - saves lots
of space and barely uses more time (especially if you use pigz
(parallelised) instead of gzip... :-)
